### ISSUE TITLE
Fix confusing `setImmidiate` section in docs, gives an error when used

### ISSUE THREAD

**Issue by ghost** [VeliovGroup/Meteor-CRON-jobs#1]
Hi! Great package for CRON jobs in meteor

The `setImmidiate` section of the docs somehow gives an error when used. 

`CRON.setImmidiate` is not a function. 

However, upon checking the JoSk package `index.js` , it turns out that the function is `setImmediate`. The docs should be edited with the correct method signature so as not to confuse other developers. Can also apply in JoSk package

**Comment by dr-dimitru** [comment]
Thank you a lot, for PR
Going to update JoSk package too.

**Comment by ghost** [comment]
No worries, happy to help. Closing this issue
