### ISSUE TITLE
Execute a task at a specific time of the day, day of the week, etc.

### ISSUE THREAD

**Issue by KoenLav** [VeliovGroup/Meteor-CRON-jobs#3]
We previously used SyncedCron (https://github.com/percolatestudio/meteor-synced-cron) but it is no longer maintained and we noticed it to, at times, skip some of our tasks without any notification.

Hence we intend to use this package for our tasks, some of which simply need to run every x minutes, but other need to run at a specific point in time (for instance every day at 04:00).

Any suggestions for implementing such a feature, or is this already available?

**Comment by dr-dimitru** [comment]
Hello @KoenLav ,

 1. Yes, running repeating tasks is easy as calling `.setInterval()` method;
 2. For tasks which should be executed at some exact point of time I'm recommend to use something like [`cron-parser` lib](https://www.npmjs.com/package/cron-parser). Use `cron-parser` to get when next time task should be executed, then get delay with `const delay = nextExecution - (+new Date());`. And set execution via `.setTimeout()` method, like:

```js
const myTask = (ready) => {
  /* task code here */
  ready();
  scheduleTask();
};

const scheduleTask = () => {
  cron.setTimeout(myTask, delay, 'myTask');
};

scheduleTask();
```

**Comment by dr-dimitru** [comment]
Hey @KoenLav ,

Have you managed to find a solution to your question?

**Comment by KoenLav** [comment]
@dr-dimitru nope, not yet, haven't had time to look into it.

Thanks for the follow up though! Will post back when I get the chance to work on it again.

**Comment by dr-dimitru** [comment]
Feel free to reopen it in case if the issue is still persists on your end.
