### ISSUE TITLE
Try to use different instances

### ISSUE THREAD

**Issue by valorloff** [VeliovGroup/Meteor-CRON-jobs#6]
Hi!
With some other tasks your cron works nicely, but with next primitive task for cleaning cart from outdate items: 
```
 const cartItems = (ready) => {
    bound(() => {
        ready();
        // some cleaning code
    });
};
  const testCartItems = cartItemsCron.setInterval(cartItems, 20 * 1000, 'cartItems');
```
i have problems:
```
[josk] [josk] [cart-itemssetInterval] Something went wrong with one of your tasks is missing.
          Try to use different instances.
           It's safe to ignore this message.
          If this task is obsolete - simply remove it with `JoSk#clearTimeout('cart-itemssetInterval')`,
          or enable autoClear with `new JoSk({autoClear: true})`

```
Please help me, thanks

**Comment by valorloff** [comment]
I guessed, there should be only one single cron for different tasks with different taskIds!

**Comment by dr-dimitru** [comment]
Hey @valorloff 

Thank you for reporting about this.
Seems like you've named (*third argument/unique key*) task `cart-item` and had stopped meteor at the moment task were executed, and moreover - renamed this task to `cartItems`, - yes this can cause this message.

If you read the error message it suggests two solutions:

 1. `new JoSk({autoClear: true})`
 2. `cartItemsCron.clearTimeout('cart-itemssetInterval')`

# 🤘

**Comment by valorloff** [comment]
Thanks friend!
Your advice makes everything work!
