### ISSUE TITLE
upgraded from 2.2.1 to 2.3.0: TypeError: CRONjob is not a constructor

### ISSUE THREAD

**Issue by valorloff** [VeliovGroup/Meteor-CRON-jobs#7]
Hi!
The devil pulled me to meteor update and now i get in my project:  
`TypeError: CRONjob is not a constructor`
I tried
`meteor remove ostrio:cron-jobs`
and
`meteor add ostrio:cron-jobs@2.2.1`
but this don't help me, no matter:
`ostrio:cron-jobs  added, version 2.3.0 `
Also linter says:
`import {CRONjob} from 'meteor/ostrio:cron-jobs'; //Module is not installed`
although at the same time your other packages (FlowRouter, Meta, Title) without errors.

Can you help me?
Thanks!

**Comment by dr-dimitru** [comment]
Hello @valorloff ,

This repository is merged to the single-rep with [npm `josk` package](https://github.com/VeliovGroup/josk), please see updated docs for meteor setup [here](https://github.com/VeliovGroup/josk#install-meteor)

Feel free to close it in case if the issue is solved on your end.

**Comment by valorloff** [comment]
I got it!
New way import is:
`import JoSk from 'meteor/ostrio:cron-jobs';`
Thanks for your excellent support!
